#!/usr/bin/env bash
# ============================================================
#  Prim'O — Admin API smoke tests + living documentation.
#  Hits every /api/admin endpoint, records request + response
#  (status + body) into RESULTS.md. Tokens are NEVER written to
#  the doc — they appear as the literal $TOKEN placeholder.
#
#  Usage:  bash run.sh            (backend must be running)
#          BASE=http://host/api bash run.sh
#  Reset seed data afterwards:  npx prisma db seed
# ============================================================
set -u

B="${BASE:-http://localhost:4000/api}"
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/RESULTS.md"
: > "$OUT"

log() { printf '%s\n' "$1" >> "$OUT"; }

# req <title> <method> <path> <token?> <body?>
# Prints a documented curl block + the real HTTP status & JSON body.
req() {
  local title="$1" method="$2" path="$3" token="$4" body="$5"
  local args=(-s -w $'\n%{http_code}' -X "$method" "$B$path")
  [ -n "$token" ] && args+=(-H "Authorization: Bearer $token")
  [ -n "$body" ] && args+=(-H 'Content-Type: application/json' -d "$body")

  local resp code json
  resp=$(curl "${args[@]}")
  code=$(printf '%s' "$resp" | tail -n1)
  json=$(printf '%s' "$resp" | sed '$d')

  log "### $title"
  log ""
  log '```bash'
  local c="curl -X $method \"$B$path\""
  [ -n "$token" ] && c="$c \\"$'\n'"  -H \"Authorization: Bearer \$TOKEN\""
  [ -n "$body" ]  && c="$c \\"$'\n'"  -H 'Content-Type: application/json' \\"$'\n'"  -d '$body'"
  log "$c"
  log '```'
  log ""
  log "**→ HTTP $code**"
  log ""
  log '```json'
  log "$(printf '%s' "$json" | jq . 2>/dev/null || printf '%s' "$json")"
  log '```'
  log ""
}

# ── tokens (captured live, never logged) ───────────────────
ADMIN_TOKEN=$(curl -s -X POST "$B/auth/login" -H 'Content-Type: application/json' \
  -d '{"email":"admin@primo.fr","password":"password123"}' \
  | jq -r '.accessToken')
MGR_TOKEN=$(curl -s -X POST "$B/auth/login" -H 'Content-Type: application/json' \
  -d '{"email":"boss@acme.fr","password":"password123"}' \
  | jq -r '.accessToken')

# ── sample ids from the live data ──────────────────────────
USERS_JSON=$(curl -s "$B/admin/users" -H "Authorization: Bearer $ADMIN_TOKEN")
ADMIN_ID=$(printf '%s' "$USERS_JSON"  | jq -r '.items[] | select(.role=="ADMIN")    | .id' | head -1)
EMP_ID=$(printf '%s' "$USERS_JSON"    | jq -r '.items[] | select(.role=="EMPLOYEE") | .id' | head -1)
DEL_EMP_ID=$(printf '%s' "$USERS_JSON"| jq -r '.items[] | select(.role=="EMPLOYEE") | .id' | sed -n '2p')
TESTCO_ID=$(printf '%s' "$USERS_JSON" | jq -r '[.items[].companyId] | map(select(. != null)) | last')
CID=$(curl -s "$B/admin/companies" -H "Authorization: Bearer $ADMIN_TOKEN" | jq -r '.items[0].id')

log "# Prim'O — Admin API test report"
log ""
log "_Generated by \`tests/admin/run.sh\` against \`$B\`. Tokens shown as \`\$TOKEN\`._"
log ""
log "## 1. Auth setup"
log ""
log "Login as admin to obtain the bearer token used below:"
log ""
log '```bash'
log "curl -X POST \"$B/auth/login\" \\"
log "  -H 'Content-Type: application/json' \\"
log "  -d '{\"email\":\"admin@primo.fr\",\"password\":\"password123\"}'"
log "# => { \"accessToken\": \"<jwt>\" }   # export TOKEN=<jwt>"
log '```'
log ""

log "## 2. Users — reads"
req "List all users (paginated)"            GET    "/admin/users"                  "$ADMIN_TOKEN" ""
req "List users filtered by role"           GET    "/admin/users?role=MANAGER&limit=5" "$ADMIN_TOKEN" ""
req "Get one user by id"                     GET    "/admin/users/$EMP_ID"          "$ADMIN_TOKEN" ""

log "## 3. Users — auth & validation guards"
req "No token -> 401"                        GET    "/admin/users"                  ""             ""
req "Manager token -> 403 (not admin)"       GET    "/admin/users"                  "$MGR_TOKEN"   ""
req "Bad UUID param -> 400"                   GET    "/admin/users/not-a-uuid"       "$ADMIN_TOKEN" ""
req "Unknown but valid UUID -> 404"          GET    "/admin/users/00000000-0000-0000-0000-000000000000" "$ADMIN_TOKEN" ""

log "## 4. Users — mutations (reversible)"
req "Reject an employee"                      PATCH  "/admin/users/$EMP_ID"          "$ADMIN_TOKEN" '{"status":"REJECTED"}'
req "Re-approve the same employee"            PATCH  "/admin/users/$EMP_ID"          "$ADMIN_TOKEN" '{"status":"APPROVED"}'
req "Self-modification blocked -> 400"        PATCH  "/admin/users/$ADMIN_ID"        "$ADMIN_TOKEN" '{"status":"REJECTED"}'
req "Reject self-delete via guard -> 400"     DELETE "/admin/users/$ADMIN_ID"        "$ADMIN_TOKEN" ""

log "## 4b. Dashboard & companies (reads)"
req "Dashboard stats"                         GET    "/admin/stats"                  "$ADMIN_TOKEN" ""
req "List companies (paginated)"              GET    "/admin/companies?page=1&limit=20" "$ADMIN_TOKEN" ""
req "Get one company by id"                   GET    "/admin/companies/$CID"         "$ADMIN_TOKEN" ""
req "Company bad UUID -> 400"                 GET    "/admin/companies/not-a-uuid"   "$ADMIN_TOKEN" ""
req "Company unknown UUID -> 404"             GET    "/admin/companies/00000000-0000-0000-0000-000000000000" "$ADMIN_TOKEN" ""
req "Create a company"                        POST   "/admin/companies"              "$ADMIN_TOKEN" '{"name":"Doc Test Co"}'
req "Create company without name -> 400"      POST   "/admin/companies"              "$ADMIN_TOKEN" '{}'

log "## 4c. Audit ledgers (global, read-only)"
req "List attributions"                       GET    "/admin/attributions?limit=5"   "$ADMIN_TOKEN" ""
req "List redemptions"                        GET    "/admin/redemptions?limit=5"    "$ADMIN_TOKEN" ""

log "## 5. Company — cascade delete then restore (reversible)"
req "Soft-delete a company (cascade)"         DELETE "/admin/companies/$TESTCO_ID"   "$ADMIN_TOKEN" ""
req "Restore the company"                     POST   "/admin/companies/$TESTCO_ID/restore" "$ADMIN_TOKEN" ""

log "## 6. Users — destructive delete (no undo; re-seed to reset)"
req "Soft-delete an employee"                 DELETE "/admin/users/$DEL_EMP_ID"      "$ADMIN_TOKEN" ""

echo "Done. See $OUT"
